### ISSUE TITLE
Баги и недочеты слайдера

### ISSUE THREAD

**Issue by mglknFSD** [dywork/range-slider#22]
1. У меня с трудом получается установить значение шага слайдера меньше 1 - значение постоянно сбрасывается на 1. На видео я пытался установить значение в 0.1 

https://user-images.githubusercontent.com/75975369/118392204-0c465f00-b641-11eb-9546-5c8dd8f079af.mp4

**Comment by mglknFSD** [comment]
2. Значения слайдера не соответствуют шагу

https://user-images.githubusercontent.com/75975369/118392282-8971d400-b641-11eb-98dd-ae39fc6f02b3.mp4

**Comment by dywork** [comment]
> 1. Значения слайдера не соответствуют шагу
> 
>  2021-05-16-12-23-23.mp4

Забыл деплой последней версии сделать)) Есть свойство maxDecimalPlace отвечающее за отображение максимального кол-во знаков после запятой:

https://user-images.githubusercontent.com/17548109/126631959-f32d140b-e329-4368-a2c2-3de06a91d679.mp4

**Comment by dywork** [comment]
> 1. У меня с трудом получается установить значение шага слайдера меньше 1 - значение постоянно сбрасывается на 1. На видео я пытался установить значение в 0.1
> 
>  2021-05-16-12-19-45.mp4

поднял на 200мс время дебаунс функции, должно помочь.

**Comment by mglknFSD** [comment]
3. Колличество видимых значений шкалы необходимо ограничить.


https://user-images.githubusercontent.com/75975369/126863970-ad7a864c-8886-40be-8695-b3c52bf9bec1.mp4

**Comment by mglknFSD** [comment]
`Макс. знаков после запятой` я понимаю почему ты это добавил но оно не решает проблему точности вычислений, а перекладывает эту головную боль на пользователя твоего слайдера. Ее можно решить и без этого. К тому же этой шкалы нет в тз.

![slider](https://user-images.githubusercontent.com/75975369/126864047-b8110b02-e7e0-4be0-be5f-c59fabac931e.jpg)

**Comment by mglknFSD** [comment]
Тултипы (область над бегунком где отображается значение) то же должны быть интерактивными. Т е должна быть возможность перетащить бегунок за этот туттип.

**Comment by mglknFSD** [comment]
Сама линия, на которой располагаются бегунки, то же должна быть интерактивна - кликнув по ней бегунок должен перемещаться в ближайшую точку слайдера
