### ISSUE TITLE
ts strict mode

### ISSUE THREAD

**Issue by Geksanit** [dywork/range-slider#37]
Привет, добавь в tsconfig `"strict": true` - этот флаг добавит больше строгих проверок и укажет на ошибки.
![image](https://user-images.githubusercontent.com/31949379/130401305-b6035d7c-7357-4b62-a122-5722eeb5d77a.png)

**Comment by dywork** [comment]
> Привет, добавь в tsconfig `"strict": true` - этот флаг добавит больше строгих проверок и укажет на ошибки.
> ![image](https://user-images.githubusercontent.com/31949379/130401305-b6035d7c-7357-4b62-a122-5722eeb5d77a.png)

привет, сделал) Если, что я всегда доступен в тг - @dywork (https://t.me/dywork)
